//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MEDESYS.Messagerie {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessagerieSoapBinding", Namespace="http://ws.solutec.esic.fr")]
    public partial class MessagerieService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback selectAllPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback selectAllbyPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessagerieService() {
            this.Url = global::MEDESYS.Properties.Settings.Default.MEDESYS_Messagerie_MessagerieService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addMessageCompletedEventHandler addMessageCompleted;
        
        /// <remarks/>
        public event selectAllPSCompletedEventHandler selectAllPSCompleted;
        
        /// <remarks/>
        public event selectAllbyPSCompletedEventHandler selectAllbyPSCompleted;
        
        /// <remarks/>
        public event getPSCompletedEventHandler getPSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.solutec.esic.fr", ResponseNamespace="http://ws.solutec.esic.fr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addMessage(MessageWS messageWS) {
            this.Invoke("addMessage", new object[] {
                        messageWS});
        }
        
        /// <remarks/>
        public void addMessageAsync(MessageWS messageWS) {
            this.addMessageAsync(messageWS, null);
        }
        
        /// <remarks/>
        public void addMessageAsync(MessageWS messageWS, object userState) {
            if ((this.addMessageOperationCompleted == null)) {
                this.addMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddMessageOperationCompleted);
            }
            this.InvokeAsync("addMessage", new object[] {
                        messageWS}, this.addMessageOperationCompleted, userState);
        }
        
        private void OnaddMessageOperationCompleted(object arg) {
            if ((this.addMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.solutec.esic.fr", ResponseNamespace="http://ws.solutec.esic.fr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("selectAllPSReturn")]
        public ProfessionnelSanteWS[] selectAllPS() {
            object[] results = this.Invoke("selectAllPS", new object[0]);
            return ((ProfessionnelSanteWS[])(results[0]));
        }
        
        /// <remarks/>
        public void selectAllPSAsync() {
            this.selectAllPSAsync(null);
        }
        
        /// <remarks/>
        public void selectAllPSAsync(object userState) {
            if ((this.selectAllPSOperationCompleted == null)) {
                this.selectAllPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselectAllPSOperationCompleted);
            }
            this.InvokeAsync("selectAllPS", new object[0], this.selectAllPSOperationCompleted, userState);
        }
        
        private void OnselectAllPSOperationCompleted(object arg) {
            if ((this.selectAllPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selectAllPSCompleted(this, new selectAllPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.solutec.esic.fr", ResponseNamespace="http://ws.solutec.esic.fr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("selectAllbyPSReturn")]
        public MessageWS[] selectAllbyPS(string idPs) {
            object[] results = this.Invoke("selectAllbyPS", new object[] {
                        idPs});
            return ((MessageWS[])(results[0]));
        }
        
        /// <remarks/>
        public void selectAllbyPSAsync(string idPs) {
            this.selectAllbyPSAsync(idPs, null);
        }
        
        /// <remarks/>
        public void selectAllbyPSAsync(string idPs, object userState) {
            if ((this.selectAllbyPSOperationCompleted == null)) {
                this.selectAllbyPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselectAllbyPSOperationCompleted);
            }
            this.InvokeAsync("selectAllbyPS", new object[] {
                        idPs}, this.selectAllbyPSOperationCompleted, userState);
        }
        
        private void OnselectAllbyPSOperationCompleted(object arg) {
            if ((this.selectAllbyPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selectAllbyPSCompleted(this, new selectAllbyPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.solutec.esic.fr", ResponseNamespace="http://ws.solutec.esic.fr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPSReturn")]
        public ProfessionnelSanteWS getPS(string idPs) {
            object[] results = this.Invoke("getPS", new object[] {
                        idPs});
            return ((ProfessionnelSanteWS)(results[0]));
        }
        
        /// <remarks/>
        public void getPSAsync(string idPs) {
            this.getPSAsync(idPs, null);
        }
        
        /// <remarks/>
        public void getPSAsync(string idPs, object userState) {
            if ((this.getPSOperationCompleted == null)) {
                this.getPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPSOperationCompleted);
            }
            this.InvokeAsync("getPS", new object[] {
                        idPs}, this.getPSOperationCompleted, userState);
        }
        
        private void OngetPSOperationCompleted(object arg) {
            if ((this.getPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPSCompleted(this, new getPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.solutec.esic.fr")]
    public partial class MessageWS {
        
        private System.Nullable<System.DateTime> dateMessageField;
        
        private string demandeField;
        
        private string destinataireField;
        
        private string expediteurField;
        
        private string idMessageField;
        
        private bool recuField;
        
        private string texteMessageField;
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dateMessage {
            get {
                return this.dateMessageField;
            }
            set {
                this.dateMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string demande {
            get {
                return this.demandeField;
            }
            set {
                this.demandeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destinataire {
            get {
                return this.destinataireField;
            }
            set {
                this.destinataireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string expediteur {
            get {
                return this.expediteurField;
            }
            set {
                this.expediteurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idMessage {
            get {
                return this.idMessageField;
            }
            set {
                this.idMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool recu {
            get {
                return this.recuField;
            }
            set {
                this.recuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string texteMessage {
            get {
                return this.texteMessageField;
            }
            set {
                this.texteMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.solutec.esic.fr")]
    public partial class ProfessionnelSanteWS {
        
        private string adresseField;
        
        private string categorieField;
        
        private string faxField;
        
        private string idPsField;
        
        private string insField;
        
        private string mailField;
        
        private string mobField;
        
        private string nomField;
        
        private string prenomField;
        
        private string specialiteField;
        
        private string telField;
        
        private string villeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string categorie {
            get {
                return this.categorieField;
            }
            set {
                this.categorieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idPs {
            get {
                return this.idPsField;
            }
            set {
                this.idPsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ins {
            get {
                return this.insField;
            }
            set {
                this.insField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mob {
            get {
                return this.mobField;
            }
            set {
                this.mobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string specialite {
            get {
                return this.specialiteField;
            }
            set {
                this.specialiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void addMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void selectAllPSCompletedEventHandler(object sender, selectAllPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selectAllPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selectAllPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProfessionnelSanteWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProfessionnelSanteWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void selectAllbyPSCompletedEventHandler(object sender, selectAllbyPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selectAllbyPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selectAllbyPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getPSCompletedEventHandler(object sender, getPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProfessionnelSanteWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProfessionnelSanteWS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591